spring:
  datasource:
    name: vm
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.253.129:3306/db1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: cjy940314

  redis:
      host: 192.168.253.129
      port: 6379
      password: cjy940314
      database: 0
      jedis:
        pool:
          max-active: 30
          max-idle: 20
          min-idle: 10
          max-wait: 1s

